### ISSUE TITLE
Lua error: bad argument #3 to '__newindex' (string expected, got nil) when pass loaded.

### ISSUE THREAD

**Issue by christf** [arcnmx/luakit-pass#2]
[  501.166783] I [lua/webview]: Requested link: https://wiki.ffm.freifunk.net/start?do=login&sectok= (text/html)
[  517.723759] E [core/common/lualib]: Lua error: bad argument #3 to '__newindex' (string expected, got nil)
                 Traceback:
                 (1) [C]                                           in function __newindex
                 (2) /home/christof/.config/luakit/pass/wm.lua:188 in function [anonymous]

**Comment by arcnmx** [comment]
Thanks! I didn't ever actually expect anyone to try and use this, hah.

This extension expects there to be a `username` or `email` field in the multiline pass file, in the same way most `pass` based tools work. See [browserpass for an example](https://github.com/dannyvankooten/browserpass#requirements). That particular website works fine for me with `:pass` as long as both a password and username exist in the file.

It seems like if the username is missing, this extension will crash instead of filling anything, and I've apparently never encountered that edge case. That's a bug!

**Comment by christf** [comment]
why not? for luakit to be a browser, a password manager must be integrated. I do not know of any other solutions to this. :)

To work around this, I ran pass edit <domainname>

Then I am presented with a file containing one line in which my password is listed. I added another line such that it looks like
```
THEPASSWORDXXXXXX
username: <my username goes here>
```

This made it work. Thank you very much for your work!

**Comment by arcnmx** [comment]
Yup, that's the correct way to do it! I've added some info to the readme regarding this, and also pushed a fix so it will at least fill in the password even if username is missing. But it's still a good idea to fill in your password files as well with the username, and much more convenient!
